stages:
  prepare:
    cmd: python src/preprocess.py
    deps:
      - data/raw/dataset.csv
      - src/preprocess.py
    outs:
      - data/processed/train.csv

  train:
    cmd: python src/train.py
    deps:
      - data/processed/train.csv
      - feature_repo/feature_repo/feature_definitions.py
      - src/train.py
    params:
      - train.model_type
      - train.n_estimators
      - train.max_depth
      - train.random_state
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - models/model.pkl
      - src/evaluate.py
    metrics:
      - metrics.json:
          cache: false 